DROP TABLE IF EXISTS USER CASCADE;
CREATE TABLE USER (
  ID  INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,,
  NAME VARCHAR(30) NOT NULL,
  EMAIL  VARCHAR(50) NOT NULL,
  BIRTHDATE DATE,
  USER_ROLE VARCHAR(30) NOT NULL
);
DROP TABLE IF EXISTS TICKET CASCADE;
CREATE TABLE TICKET(
  ID INTEGER PRIMARY KEY,
  IS_PURCHASED NUMBER(0,1)
);
DROP TABLE IF EXISTS EVENT CASCADE;
CREATE TABLE EVENT(
  ID  INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  RATING VARCHAR(10),
  BASEPRICE DECIMAL(4,2)
);
DROP TABLE IF EXISTS USER_TICKET_MP CASCADE;
CREATE TABLE USER_TICKET_MP(
  USER_ID INTEGER,
  TICKET_ID INTEGER
);
DROP TABLE IF EXISTS EVENT_DATE_MP CASCADE;
CREATE TABLE EVENT_DATE_MP(
  EVENT_ID INTEGER,
  DATE DATE NOT NULL DEFAULT GETDATE()
);
DROP TABLE IF EXISTS EVENT_TICKET_MP CASCADE;
CREATE TABLE EVENT_TICKET_MP(
  EVENT_ID INTEGER,
  TICKET_ID INTEGER
);
