DROP TABLE IF EXISTS USER CASCADE;
CREATE TABLE USER (
  ID  INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  EMAIL  VARCHAR(50) NOT NULL,
  BIRTHDATE DATE,
  USER_ROLE VARCHAR(30) NOT NULL
);
ALTER TABLE USER ADD CONSTRAINT USER_ID_PK PRIMARY KEY (ID);

DROP TABLE IF EXISTS TICKET CASCADE;
CREATE TABLE TICKET(
  ID INT NOT NULL AUTO_INCREMENT,
  IS_PURCHASED BOOLEAN
);
ALTER TABLE TICKET ADD CONSTRAINT TICKET_ID_PK PRIMARY KEY (ID);

DROP TABLE IF EXISTS EVENT CASCADE;
CREATE TABLE EVENT(
  ID  INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  RATING VARCHAR(10),
  BASEPRICE DECIMAL(4,2)
);
ALTER TABLE EVENT ADD CONSTRAINT EVENT_ID_PK PRIMARY KEY (ID);

DROP TABLE IF EXISTS USER_TICKET_MP CASCADE;
CREATE TABLE USER_TICKET_MP(
  USER_ID INTEGER,
  TICKET_ID INTEGER
);

DROP TABLE IF EXISTS EVENT_DATE_MP CASCADE;
CREATE TABLE EVENT_DATE_MP(
  EVENT_ID INTEGER,
  DATE DATE NOT NULL DEFAULT GETDATE()
);

DROP TABLE IF EXISTS EVENT_TICKET_MP CASCADE;
CREATE TABLE EVENT_TICKET_MP(
  EVENT_ID INTEGER,
  TICKET_ID INTEGER
);
